# Generated by Django 5.0.2 on 2024-02-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopNow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='card',
            new_name='shopCard',
        ),
    ]
